server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureak: true
    fetch-resgistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost